export { default as CarritoPage } from "./Carrito"
export { default as ComprasPage } from "./Compras"
export { default as CrearCuentaPage } from "./CrearCuenta"
export { default as IngresarCuentaPage } from "./IngresarCuenta"
export { default as PresentacionPage } from "./presentacion"
